name: Shutdown Cloud Run Demo

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-central2
  SERVICE_NAME: fastapi-backend

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Delete Cloud Run Service'
        run: |
          gcloud run services delete ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --quiet
